//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int id { get; set; }
        public System.DateTime dateBegin { get; set; }
        public System.DateTime dateEnd { get; set; }
        public int purposeId { get; set; }
        public int employeeId { get; set; }
        public int visitorId { get; set; }
        public Nullable<System.DateTime> appointedDate { get; set; }
        public Nullable<System.TimeSpan> appointedTime { get; set; }
        public int statusId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Purpose Purpose { get; set; }
        public virtual Status Status { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
