//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeeperPRO.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogAutho
    {
        public int id { get; set; }
        public System.DateTime dateTimeLog { get; set; }
        public int employeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
